### ISSUE TITLE
Gerber Files for the PCB

### ISSUE THREAD

**Issue by F4BR1C3xD** [stanleyondrus/LedBoxV2#3]
Hello,

I really appreciate your fantastic work!

Is there any chance to get the gerber files? So I can order your great design on jlc?
Is there maybe a partlist too?

Thanks for your help!

**Comment by stanleyondrus** [comment]
Hey. Thank you for your support!
I have not published the gerber files yet, as I am working on a new version of the board. But I will let you know if that changes.
Stay tuned!

**Comment by F4BR1C3xD** [comment]
Hey,
Thank you for your feedback. I'm really looking forward to it.
Then I will postpone my LED projects for the time being :D

Thank you very much!
