### ISSUE TITLE
Boot mode

### ISSUE THREAD

**Issue by xrtze** [stanleyondrus/LedBoxV2#4]
According to the schematics, GPIO0 is pulled low directly to GND without a 10k resistor. How will this work? Since GPIO0 has a 45k pullup resistor, how would you be able to pull it low and enter boot mode?

**Comment by stanleyondrus** [comment]
GPIO0 is connected to a push button (SW1), which can be used to connect it to ground and enter the bootloader mode. As you mentioned, there is an internal pull-up resistor, so no extra passives are needed.
