### ISSUE TITLE
LedBox V2 compatibility w/ WLED 0.14.x?

### ISSUE THREAD

**Issue by graste** [stanleyondrus/LedBoxV2#5]
Hi,

I just updated my LedBox V2 to the firmware version 0.13.3. Many thanks for this nifty little box!

Reading https://kno.wled.ge/advanced/audio-reactive/ I was wondering whether I could nowadays pick any (sound reactive) WLED version 0.14.x from e.g their [web based installer](https://wled-install.github.io/) to update on the LedBox V2 and what your recommended (sound reactive) versions and microphone settings would be. The same as the original sound settings from the firmwares of this repo?

Any hints appreciated!

**Comment by stanleyondrus** [comment]
Hi @graste,

Thank you for support!

Yes, it is correct. Starting from version 0.14.0, WLED contains SR functionality as a user mod, so you can flash it directly.
However, make sure that the binary contains the required functionalities. If you are using a binary from the [web based installer](https://wled-install.github.io/), select the one for ESP32 (4MB Flash) marked "Audio reactive Usermod".

If you uncheck "Clean install" during the update, it will keep all the pin allocations that are specific to this module. Alternatively, you can re-assign them yourself according to this table :
![https://stanleyprojects.com/projects/ledbox_v2](https://stanleyprojects.com/projects/ledbox_v2/table2.png)

In the AudioReactive setting page, the mic type must be set to "Generic I2S", and mic pins allocated according to the table above.

Feel free to reach out again if you encounter any difficulties.

**Comment by graste** [comment]
Thanks for the fast and helpful reply!
